version: '1'
services:
  web:
    build: .
    command: bash -c "python app/manage.py makemigrations && python app/manage.py migrate && python app/manage.py runserver"
    container_name: django-app
    volumes:
      - .:/django-app
    ports:
      - "8000:8000"
  