# Generated by Django 4.1.3 on 2022-12-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_name', models.CharField(max_length=100)),
                ('auction_image', models.ImageField(blank=True, max_length=500, upload_to='images')),
                ('auction_desc', models.CharField(max_length=200)),
                ('auction_price', models.PositiveIntegerField()),
                ('auction_running_price', models.PositiveIntegerField()),
                ('auction_startDate', models.DateTimeField()),
                ('auction_endDate', models.DateTimeField()),
            ],
        ),
    ]
