# Generated by Django 4.1.3 on 2022-12-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auction_auction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_image',
            field=models.ImageField(blank=True, max_length=500, upload_to='images'),
        ),
    ]
