# Generated by Django 4.1.4 on 2022-12-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auction_bider_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.CharField(default='', max_length=100)),
                ('winner_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('winning_price', models.PositiveIntegerField()),
                ('winning_date', models.DateTimeField()),
                ('payment', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='auction',
            name='bider_user',
        ),
        migrations.AddField(
            model_name='auction',
            name='bider_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auction',
            name='bider_user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
