# Generated by Django 4.1.3 on 2023-01-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_winner_winner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='winner_name',
            field=models.CharField(max_length=25),
        ),
    ]
